### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by jdzhey** [bitfreee/movie-web-kickstart#17]
How to make it work?
i put my  G-XXXXXXXXXX to the config but google analytics cant receive signal from the site

**Comment by bitfreee** [comment]
@jdzhey: Have you set NEXT_PUBLIC_GOOGLE_ANALYTICS_ID environment variable in Vercel?

**Comment by jdzhey** [comment]
yeah. but i tried to redeploy, and it is fine now. 

thanks
